version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # Ini sudah benar
      MYSQL_DATABASE: webportofolio6
      # HAPUS BARIS INI: MYSQL_USER: root
      # HAPUS JUGA BARIS MYSQL_PASSWORD jika ada
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Atau "3306:3306" jika itu yang Anda inginkan dan portnya bebas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Ini sudah benar (tanpa user/password)
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  db_data: